---
- name: Install Docker
  hosts: docker
  become: true

  vars:
    ansible_distribution_release: bionic
    theuser: andra

  tasks:
  - name: Ensure old versions of Docker are not installed.
    package:
      name:
      - docker
      - docker-engine
      state: absent
      
  - name: Update APT package cache
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400



  - name: Update the apt package index and install packages to allow apt to use a repository over HTTPS.
    apt: 
      name:    
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common
      state: latest 
      update_cache: yes
      
  - name: Add Docker’s official GPG key
    shell: 
      cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#    apt_key: 
#      keyserver: keyserver.ubuntu.com 
#      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
  
  
  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=600


  - name: Install Docker CE
    apt:
      name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      state: present
      update_cache: yes
      
  - name: add docker goup
    user:
      name: {{ theuser }}
      append: yes
      groups: docker
      
  handlers:
  - name: Restart Docker
    systemd:
      name: docker
      state: restarted
