user: 
  name: andra
  full_name: Andra Necula
  passwd: $1$.6xAMhZ6$TLg6yWl36xoov/tZEeNG30
  pub_key: ssh-rsa ***




vm: 
  name: mulan
  cpu: 1
  mem: 2048
  disk: 5G
  bridge: virbr0
  net: 
    ip: 192.168.122.156/24
    gateway: 192.168.1.1
    #netmask:  255.255.255.0
    domain: github.io
    dns: 
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 9.9.9.9

domain: github.io


